---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api-ksa
      containers:
        - name: api
          image: api:0.0.1
          ports:
            - name: http-api
              containerPort: 8080
